### ISSUE TITLE
Unable to open repo on Linux64

### ISSUE THREAD

**Issue by dfarmer** [WolframResearch/GitLink#1]
I downloaded and installed the Paclet on my Windows and Linux machines. Windows works fine, but when I try to GitOpen any repo (I tried several including newly created ones) I just get $Failed. I suspect that libgit2 is somehow not loading properly, but without a real error message I'm not sure how to provide a more helpful bug report. Are there some additional steps I can take to create a more useful report (or are there any known issues on 64bit Linux (Ubuntu 14.04 distro).

**Comment by szhorvat** [comment]
In case someone will find this useful:

Ubuntu 14.04 has an old version of gcc, specifically 4.8.2.  C++ stuff compiled with newer gcc won't work on Ubuntu 14.04 due to ABI incompatibilities.

It may be possible to use a newer GCC and compile for the older ABI, see here: https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_dual_abi.html and `_GLIBCXX_USE_CXX11_ABI`.  I have not personally tried this yet. I simply used an older gcc to compile my projects for compatibility with old Linux distros.

@dfarmer  I suggest you compile GitLink yourself to be able to use it right now.

**Comment by szhorvat** [comment]
There don't seem to be any pre-compiled binaries for Linux.  I think the only option is to compile it ourselves on Linux.

**Comment by jfultz** [comment]
Yes, you're right...the Linux binaries seem to be missing (I didn't believe it until I saw it for myself).  I have no idea how that happened...this was rolled from our Jenkins build system which shouldn't ever do that.  I'm indisposed today, but I'll look at this when I get a chance and update the release.

**Comment by dfarmer** [comment]
I'm pretty sure I verified this was fixed in a subsequent release.
